
.rules:
    rules:
        - if: $CI_COMMIT_REF_SLUG =~ "master"
          when: manual 


.docker:
    stage: prepare
    extends: .rules
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build . -t $IMAGE_TAG
        - docker push $IMAGE_TAG

        




